-- GATE OS - validacao manual Supabase antes do push
-- Data: 2026-06-09
--
-- NAO executar este arquivo inteiro de uma vez.
-- Leia as secoes abaixo e execute apenas os blocos aprovados no Supabase SQL Editor.
-- Este arquivo nao cria usuario Supabase Auth e nao contem senha.

-- =========================================================
-- A. COMANDOS SQL SEGUROS PARA EXECUTAR AGORA
-- =========================================================
-- Estes comandos sao idempotentes e nao removem dados.
-- Antes de executar, confirme o e-mail real do admin em Auth > Users.

-- A1. Vincular usuario admin ja criado no Supabase Auth em public.users.
-- Troque admin@gate.example pelo e-mail real criado no Supabase Auth.
--
-- insert into public.users (id, email, name, role, created_at)
-- select
--   id,
--   email,
--   coalesce(raw_user_meta_data->>'name', raw_user_meta_data->>'full_name', 'Administrador GATE'),
--   'admin',
--   now()
-- from auth.users
-- where email = 'admin@gate.example'
-- on conflict (id) do update
-- set
--   email = excluded.email,
--   name = excluded.name,
--   role = 'admin';

-- A2. Confirmar/criar buckets privados esperados.
-- Seguro por usar on conflict do nothing. Nao altera buckets existentes.
--
-- insert into storage.buckets (id, name, public)
-- values
--   ('gate-documents', 'gate-documents', false),
--   ('gate-contracts', 'gate-contracts', false),
--   ('gate-legal', 'gate-legal', false)
-- on conflict (id) do nothing;

-- A3. Consultas de verificacao apos A1/A2.
--
-- select id, email, name, role, created_at
-- from public.users
-- where email = 'admin@gate.example';
--
-- select id, name, public
-- from storage.buckets
-- where id in ('gate-documents', 'gate-contracts', 'gate-legal')
-- order by id;

-- =========================================================
-- B. COMANDOS QUE PRECISAM REVISAO ANTES DE EXECUTAR
-- =========================================================
-- Estes comandos definem uma matriz ampla: qualquer usuario authenticated
-- consegue select/insert/update nas tabelas internas listadas.
-- Execute somente se este for o modelo de acesso aprovado para a GATE.
-- Para escopo por empresa, cargo ou dono do registro, adapte using/with check
-- para claims, public.users.role ou colunas de ownership.

-- B1. RLS autenticado para tabelas operacionais internas.
--
-- do $$
-- declare
--   relation_name text;
-- begin
--   foreach relation_name in array array[
--     'users',
--     'clients',
--     'contracts',
--     'contract_equipment',
--     'installments',
--     'financial_entries',
--     'dre_categories',
--     'cost_centers',
--     'bank_accounts',
--     'equipment',
--     'assets',
--     'maintenance_orders',
--     'legal_cases',
--     'legal_updates',
--     'legal_agreement_installments',
--     'documents',
--     'partners',
--     'partner_entries',
--     'dre_monthly_closings',
--     'dre_manual_adjustments',
--     'notifications'
--   ] loop
--     execute format('alter table public.%I enable row level security', relation_name);
--
--     execute format('drop policy if exists gate_authenticated_select on public.%I', relation_name);
--     execute format('drop policy if exists gate_authenticated_insert on public.%I', relation_name);
--     execute format('drop policy if exists gate_authenticated_update on public.%I', relation_name);
--
--     execute format(
--       'create policy gate_authenticated_select on public.%I for select to authenticated using (auth.uid() is not null)',
--       relation_name
--     );
--     execute format(
--       'create policy gate_authenticated_insert on public.%I for insert to authenticated with check (auth.uid() is not null)',
--       relation_name
--     );
--     execute format(
--       'create policy gate_authenticated_update on public.%I for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null)',
--       relation_name
--     );
--   end loop;
-- end $$;

-- B2. Deletes apenas onde a UI realmente oferece exclusao.
-- Revise antes, pois delete e destrutivo.
--
-- drop policy if exists gate_authenticated_delete on public.dre_manual_adjustments;
-- create policy gate_authenticated_delete on public.dre_manual_adjustments
--   for delete to authenticated
--   using (auth.uid() is not null);
--
-- drop policy if exists gate_authenticated_delete on public.financial_entries;
-- create policy gate_authenticated_delete on public.financial_entries
--   for delete to authenticated
--   using (auth.uid() is not null);

-- B3. Storage policies autenticadas.
-- Revise se todos os usuarios autenticados podem ler/enviar arquivos nos tres buckets.
--
-- drop policy if exists gate_storage_read on storage.objects;
-- create policy gate_storage_read on storage.objects
--   for select to authenticated
--   using (bucket_id in ('gate-documents', 'gate-contracts', 'gate-legal'));
--
-- drop policy if exists gate_storage_upload on storage.objects;
-- create policy gate_storage_upload on storage.objects
--   for insert to authenticated
--   with check (bucket_id in ('gate-documents', 'gate-contracts', 'gate-legal'));
--
-- drop policy if exists gate_storage_update on storage.objects;
-- create policy gate_storage_update on storage.objects
--   for update to authenticated
--   using (bucket_id in ('gate-documents', 'gate-contracts', 'gate-legal'))
--   with check (bucket_id in ('gate-documents', 'gate-contracts', 'gate-legal'));

-- B4. Acesso publico por token de contrato.
-- Manter anon somente para a rota publica /cliente/contrato/[token].
-- Revise dependencias de leitura do cliente/equipamentos/parcelas exibidas nessa rota.
--
-- drop policy if exists public_contract_read_by_enabled_token on public.contracts;
-- create policy public_contract_read_by_enabled_token on public.contracts
--   for select to anon
--   using (public_access_enabled = true and public_access_token is not null);

-- =========================================================
-- C. COMANDOS QUE NAO DEVEM SER EXECUTADOS AUTOMATICAMENTE
-- =========================================================
-- C1. Criacao de usuario em Supabase Auth.
-- Criar pelo painel Auth > Users ou por Admin API com SERVICE_ROLE em ambiente seguro.
-- Nunca colocar senha fixa no frontend, SQL versionado ou variaveis NEXT_PUBLIC.
--
-- C2. Policies anon amplas.
-- Nao recriar policies de homologacao como select/insert/update anon em tabelas internas.
-- O sistema interno deve usar role authenticated.
--
-- C3. Drop de tabelas, views, buckets, objetos de Storage ou policies desconhecidas.
-- Nao executar em validacao pre-push.
